CREATE TABLE public.permissoes (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(60) not null,
	nome varchar(100) not null,
	CONSTRAINT permissoes_pkey PRIMARY KEY (id)
);

CREATE TABLE public.grupos_permissoes (
	permissao_id int8 NOT NULL,
	grupo_id int8 NOT NULL,
	CONSTRAINT grupos_permissoes_pkey PRIMARY KEY (grupo_id, permissao_id)
);

ALTER TABLE public.grupos_permissoes ADD CONSTRAINT grupos_permissoes_grupo_id_fk FOREIGN KEY (grupo_id) REFERENCES public.grupos(id);
ALTER TABLE public.grupos_permissoes ADD CONSTRAINT grupos_permissoes_grupo_id_fk_ FOREIGN KEY (permissao_id) REFERENCES public.permissoes(id);