CREATE TABLE public.usuarios (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(120) NOT NULL,
	email varchar(120) NOT NULL,
	senha varchar(120) NOT NULL,
	CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);